OS-8604 illumos-extra needs to deal with configure-time issues of gcc14
TritonDataCenter/illumos-extra pull request #144
Opened 2024-12-23 15:38 UTC by danmcd

A joint @tsoome and @danmcd effort. Initial wsdiff analysis in the ticket.

2024-12-25 12:39 UTC, tsoome approved these changes

2024-12-25 12:40 UTC, tsoome approved these changes

2024-12-30 20:16 UTC, bahamat requested changes
The patch files should have explicit sequencing. I.e., a 4-digit numerical prefix.

2024-12-31 05:01 UTC, danmcd commented
> The patch files should have explicit sequencing. I.e., a 4-digit numerical prefix.

There are quite a few.  Will need to build overnight.  Watch Slack for details.

2024-12-31 14:26 UTC, danmcd commented
Rearranged patches per @bahamat .  Built on Jenkins last night, running on Kebecloud and my big NUC.

2025-01-03 16:31 UTC, tsoome approved these changes

2025-01-03 20:26 UTC, danmcd commented
> The patch files should have explicit sequencing. I.e., a 4-digit numerical prefix.

This one needs clearing.

2025-01-04 04:43 UTC, bahamat approved these changes

2025-01-04 04:54 UTC, merged